String.prototype.trim=function(){return this.replace(/^\s\s*/,"").replace(/\s\s*$/,"")};window.sentlog=window.sentlog||{referrer:!1};window.site_name=window.site_name||"58";var json_trackPagetype="NA",json_trackURL="NA",json_trackParams="NA",json_trackPageview="NA",json_sid="NA";
"undefined"!=typeof ____json4fe&&("_trackPagetype"in ____json4fe&&(json_trackPagetype=____json4fe._trackPagetype),"_trackURL"in ____json4fe&&(json_trackURL=____json4fe._trackURL),"_trackParams"in ____json4fe&&(json_trackParams=____json4fe._trackParams),"_trackPageview"in ____json4fe&&(json_trackPageview=____json4fe._trackPageview),"sid"in ____json4fe&&(json_sid=____json4fe.sid));window.tgreg=window.tgreg||-1;window._trackURL=window._trackURL||json_trackURL||"NA";
window._trackParams=window._trackParams||json_trackParams||"NA";var referrer=encodeURIComponent(document.referrer),pagetypeTmp,post_countTmp,cateTmp="",areaTmp="",GA_pageviewTmp="",ROITmp="";
if("NA"!=_trackURL){var trackJsonStr=eval("("+_trackURL+")");trackJsonStr.pagetype&&(pagetypeTmp=trackJsonStr.pagetype);trackJsonStr.post_count&&(post_countTmp=trackJsonStr.post_count);trackJsonStr.cate&&(cateTmp=trackJsonStr.cate);trackJsonStr.area&&(areaTmp=trackJsonStr.area);trackJsonStr.GA_pageview&&(GA_pageviewTmp=trackJsonStr.GA_pageview);trackJsonStr.ROI&&(ROITmp=trackJsonStr.ROI)}window.page_type=window.page_type||pagetypeTmp||json_trackPagetype||"NA";
window.post_count=window.post_count||post_countTmp||-1;"NA"!=json_trackPageview&&insertIntoTrackURL("GA_pageview",json_trackPageview);window._gaq=window._gaq||[];var GTID=Math.random(),GTID=(new Date).valueOf()+""+GTID;"NA"!=json_sid&&""!=json_sid&&(GTID=json_sid);var ClickID=1,curURL=window.location.href;insertIntoTrackURL("GTID",GTID);
if(window.$){(function(){-1!=(_trackURL||"NA").indexOf("'pagetype':'home'")&&$("[href]").bind("click",function(b){var a=$(this).attr("href"),c=$(this).offset().top,d=$(this).offset().left;clickLog("from=heatmap:"+a+"&tagX="+d+"&tagY="+c+"&mouseX="+b.pageX+"&mouseY="+b.pageY)})})();(function(){$("[tongji_id]").bind("click",function(b){var a=b.srcElement?b.srcElement:b.target;"A"==a.tagName.toUpperCase()&&(b=$(a).attr("href")||"#",a=$(a).text(),-1==b.indexOf("javascript:")&&"#"!=b.substring(0,1)&&clickLog("from="+
$(this).attr("tongji_id")+"&text="+encodeURIComponent(a)+"&to="+encodeURIComponent(b)+"&tongji_type=tongji_id"))})})();(function(){$("[tongji_tag]").bind("click",function(){var b=$(this).attr("tongji_tag"),a=$(this).text().trim();clickLog("from="+b+"&text="+encodeURIComponent(a)+"&tongji_type=tongji_tag")})})();try{$("#zp_recommend").delegate&&$("#zp_recommend").delegate("a","click",function(){var b=ClickID;if("NO"==filterList(curURL)&&-1!=curURL.indexOf(".58.com")){var a=$(this).attr("href")||"#";
-1!=a.indexOf("javascript:")||"#"==a.substring(0,1)||"NO"!=filterList(a)||"/"!=a.substring(0,1)&&-1==a.indexOf(".58.com")||(a.match(/[\?&]PGTID=[^&]*&ClickID=\d*/)?$(this).attr("href",a.replace(/PGTID=[^&]*&ClickID=\d*/,"PGTID="+GTID+"&ClickID="+b)):$(this).attr("href",a.trim()+(-1==a.indexOf("?")?"?":"&")+"PGTID="+GTID+"&ClickID="+b))}})}catch(e$$14){}$("a").bind("click",function(){var b=ClickID;if("NO"==filterList(curURL)&&-1!=curURL.indexOf(".58.com")){var a=$(this).attr("href")||"#";-1!=a.indexOf("javascript:")||
"#"==a.substring(0,1)||"NO"!=filterList(a)||"/"!=a.substring(0,1)&&-1==a.indexOf(".58.com")||(a.match(/[\?&]PGTID=[^&]*&ClickID=\d*/)?$(this).attr("href",a.replace(/PGTID=[^&]*&ClickID=\d*/,"PGTID="+GTID+"&ClickID="+b)):$(this).attr("href",a.trim()+(-1==a.indexOf("?")?"?":"&")+"PGTID="+GTID+"&ClickID="+b))}})}
if(-1!=curURL.indexOf("post.58.com")||!sentlog.referrer){_trackParams=format_trackParams(_trackParams);_trackParams=encodeURIComponent(_trackParams);var logmsg="tag=pvstatall&referrer="+referrer+"&type="+page_type+"&post_count="+post_count+"&_trackParams="+_trackParams;if("detail"==page_type||"jianli_detail"==page_type)try{if(logmsg=logmsg+"&userid="+____json4fe.userid,"phone"in ____json4fe&&(logmsg=logmsg+"&huzhuan="+____json4fe.phone),0<tgreg&&(logmsg=logmsg+"&tgreg="+tgreg),"infoid"in ____json4fe){var infoid=
____json4fe.infoid;insertIntoTrackURL("infoid",infoid)}}catch(e$$15){}try{if("version"in ____json4fe&&(logmsg=logmsg+"&version="+____json4fe.version),"smsc"in ____json4fe&&(logmsg=logmsg+"&smsc="+____json4fe.smsc),"start"in ____json4fe&&(logmsg+="&loadtime="+((new Date).getTime()-____json4fe.start)),"supplycount"in ____json4fe)for(var attr in ____json4fe.supplycount)logmsg=logmsg+"&supplycount."+attr+"="+____json4fe.supplycount[attr]}catch(e$$16){}try{logmsg=logmsg+"&window_size="+document.documentElement.clientWidth+
"x"+document.documentElement.clientHeight}catch(e$$17){}try{var cookie_utm_source=getcookie("utm_source")||"",cookie_utm_campaign=getcookie("utm_campaign")||"",cookie_spm=getcookie("spm")||"";insertIntoTrackURL("utm_source",cookie_utm_source);logmsg=logmsg+"&utm_source="+cookie_utm_source;insertIntoTrackURL("utm_campaign",cookie_utm_campaign);insertIntoTrackURL("spm",cookie_spm);var init_refer=referrer,cookie_init_refer=getcookie("init_refer"),cookie_new_session=getcookie("new_session");cookie_new_session&&
""!=cookie_new_session?(setcookie_session("new_session","0"),setcookie_session("init_refer",cookie_init_refer),insertIntoTrackURL("init_refer",cookie_init_refer),insertIntoTrackURL("new_session","0")):(setcookie_session("new_session","1"),setcookie_session("init_refer",init_refer),insertIntoTrackURL("init_refer",init_refer),insertIntoTrackURL("new_session","1"));var cookie_new_uv=getcookie("new_uv");cookie_new_uv&&""!=cookie_new_uv?cookie_new_session&&""!=cookie_new_session||cookie_new_uv++:cookie_new_uv=
1;setcookie("new_uv",cookie_new_uv,365);insertIntoTrackURL("new_uv",cookie_new_uv);logmsg=logmsg+"&_ga_utma=1.1.1.1.1."+cookie_new_uv}catch(e$$18){}"NA"!=_trackURL&&(logmsg=logmsg+"&trackURL="+_trackURL);ajaxlog_new(logmsg);"NA"!=_trackURL&&"NA"!=pagetypeTmp&&"list"==pagetypeTmp&&ajaxlog_pclistshow(_trackURL);sentlog.referrer=!0}function setcookie(b,a,c){var d=new Date;d.setTime(d.getTime()+864E5*c);document.cookie=b+"="+escape(a)+"; expires="+d.toGMTString()+"; domain=.58.com; path=/"}
function setcookie_session(b,a){var c=new Date;c.setTime(c.getTime()+18E5);document.cookie=b+"="+escape(a)+"; expires="+c.toGMTString()+"; domain=.58.com; path=/"}function getcookie(b){var a;return(a=document.cookie.match(RegExp("(^| )"+b+"=([^;]*)(;|$)")))?unescape(a[2]):""}function ajaxsend(b){(new Image).src=b}
function ajaxlog(b){ajaxsend(document.location.protocol+"//track.58.com/empty.js.gif?site_name="+site_name+"&"+b+"&rand="+Math.random());ajaxsend(document.location.protocol+"//tracklog1.58.com/pc/empty.js.gif?site_name="+site_name+"&"+b+"&rand="+Math.random())}
function ajaxlog_new(b){var a=Math.random();ajaxsend(document.location.protocol+"//tracklog1.58.com/pc/empty.js.gif?fromid=referrer4&site_name="+site_name+"&"+b+"&rand_id="+a);var c=_trackURL||"NA";if("job"==ROITmp||"detail"==page_type||"jianli_detail"==page_type)"job"!=ROITmp&&-1==c.indexOf("'cate':'9224")&&-1==c.indexOf("'cate':'9225")&&-1==c.indexOf("'cate':'13941")&&-1==c.indexOf("'cate':'13952")||ajaxsend(document.location.protocol+"//dialog.58.com/transfer?DIATag=PCTrack&"+b+"&rand_id="+a);
"list"==pagetypeTmp&&(b=GA_pageviewTmp.indexOf("?key="),a="",-1!=b&&(a=GA_pageviewTmp.substring(b+5)),ajaxsend(document.location.protocol+"//gdt.cm.58.com/gdtcm?city="+areaTmp+"&cate="+cateTmp+"&key="+a+"&plat=PC"))}function ajaxlog2(b){ajaxlog(b)}function ajaxlogr(b){ajaxsend(document.location.protocol+"//tracklog1.58.com/pc/click/listclicklog?site_name="+site_name+"&"+b+"&trackURL="+_trackURL+"&ClickID="+ClickID+"&referrer="+referrer+"&rand="+Math.random());setTimeout("ClickIDPlus()",300)}
function format_trackParams(b){if("NA"==b)return b;try{for(var a=[],c=0,d=b.length;c<d;c++)a.push(b[c].I+":"+b[c].V.replace(/\|/g,"*"));return a.join("@@")}catch(e){return"error"}}
function clickLog(b){var a=getcookie("bangbangid");a&&""!=a||(a="");var c=ClickID;ajaxsend(document.location.protocol+"//tracklog1.58.com/pc/click/empty.js.gif?site_name="+site_name+"&tag=pvsiters&"+b+"&trackURL="+_trackURL+"&ClickID="+c+"&bangbangid="+a+"&referrer="+referrer+"&rand="+Math.random());ajaxsend(document.location.protocol+"//tracklog1.58.com/PCv1/click/empty.js.gif?site_name="+site_name+"&tag=pcclick&"+b+"&trackURL="+_trackURL+"&ClickID="+c+"&bangbangid="+a+"&referrer="+referrer+"&rand="+
Math.random());"job"!=ROITmp&&-1==b.indexOf("&ROI=")||ajaxsend(document.location.protocol+"//dialog.58.com/transfer?DIATag=PCClick&"+b+"&trackURL="+_trackURL+"&ClickID="+c+"&bangbangid="+a+"&referrer="+referrer+"&rand="+Math.random());setTimeout("ClickIDPlus()",300)}function ClickIDPlus(){ClickID+=1}
function showLog(b){var a=getcookie("bangbangid");a&&""!=a||(a="");ajaxsend(document.location.protocol+"//dialog.58.com/transfer?DIATag=PCTuijianShow&"+b+"&trackURL="+_trackURL+"&bangbangid="+a+"&referrer="+referrer+"&rand="+Math.random())}function filterList(b){var a=".58.com.cn portal.58.com faw-vw-dasweltauto.58.com 5858.com lieche.58.com dict.58.com/xiaoqu about.58.com".split(" "),c;for(c in a)if(-1!=b.indexOf(a[c]))return"YES";return"NO"}
function insertIntoTrackURL(b,a){if(b){var c=_trackURL;try{if("NA"!=_trackURL&&-1!=_trackURL.indexOf("{")){var d=_trackURL.indexOf("{");_trackURL=_trackURL.substring(0,d+1)+"'"+b+"':'"+a+"',"+_trackURL.substring(d+1)}else _trackURL="{'"+b+"':'"+a+"'}"}catch(e){_trackURL=c}}}
function ajaxlog_pclistshow(b){try{if(window.$){var a=getcookie("bangbangid");a&&""!=a||(a="");var c=Math.random();data_arr=[];"NA"!=cateTmp&&cateTmp.split(",");for(var d=$("[logr]"),e=0,h=d.length;e<h;e++)if($(d[e]).attr("logr")){var f=[],g="",k=$(d[e]).attr("logr").split("_");f.push(k[0],k[1],k[2],k[3]);var l=$(d[e]).attr("_pos"),n=e+1,p=$(d[e]).attr("sortid"),q=$(d[e]).attr("infoproperty"),m=k[k.length-1];m&&-1!=m.indexOf("ses^")&&(m=m.replace("ses^","ses:"),g+=m);p&&(g+="@sortid:"+p);n&&(g+="@pos:"+
n);l&&(g+="@npos:"+l);q&&(g+="@infoproperty:"+q);""!=g&&f.push(g);data_arr.push(f.join("_"))}ajaxsend(document.location.protocol+"//tracklog1.58.com/PCv1/listshow/empty.js.gif?tag=pclistshow&fromid=referrer4&bangbangid="+a+"&referrer="+referrer+"&site_name="+site_name+"&info_data="+data_arr.join(",")+"&trackURL="+b+"&rand_id="+c)}}catch(r){ajaxsend(document.location.protocol+"//tracklog1.58.com/PCv1/listshow/empty.js.gif?tag=pclistshow&fromid=referrer4&Error="+r)}}
if(window.$)try{(function(){$("[logr]").find("a").bind("click",function(){var b=getcookie("bangbangid");b&&""!=b||(b="");var a="",c=ClickID,d=Math.random(),e=$(this).parents("[logr]"),a=[],h="",f=e.attr("logr").split("_");a.push(f[0],f[1],f[2],f[3]);var g=e.attr("_pos"),k=$("[logr]").index(e)+1,l=e.attr("sortid"),e=e.attr("infoproperty");(f=f[f.length-1])&&-1!=f.indexOf("ses^")&&(f=f.replace("ses^","ses:"),h+=f);l&&(h+="@sortid:"+l);k&&(h+="@pos:"+k);g&&(h+="@npos:"+g);e&&(h+="@infoproperty:"+e);
""!=h&&a.push(h);a=a.join("_");ajaxsend(document.location.protocol+"//tracklog1.58.com/PCv1/listclick/empty.js.gif?tag=pclistclick&fromid=referrer4&bangbangid="+b+"&referrer="+referrer+"&site_name="+site_name+"&info_data="+a+"&trackURL="+_trackURL+"&ClickID="+c+"&rand_id="+d);setTimeout("ClickIDPlus()",300)})})()}catch(e$$22){ajaxsend(document.location.protocol+"//tracklog1.58.com/PCv1/listclick/empty.js.gif?tag=pclistclick&fromid=referrer4&Error="+e$$22)};
